spring:
  application:
    name: echo
  datasource:
    url: jdbc:mysql://localhost:3307/echo_db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: echouser
    password: ${DB_PASSWORD} #echouser에 대한 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # 개발 중에는 update, 운영에서는 validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

openai:
  api:
    url: https://api.openai.com/v1
  whisper:
    model: whisper-1
    language: ko
